2021-08-31 22:28:38,897 INFO    MainThread:20698 [internal.py:wandb_internal():88] W&B internal server running at pid: 20698, started at: 2021-08-31 22:28:38.896971
2021-08-31 22:28:38,898 INFO    WriterThread:20698 [datastore.py:open_for_write():80] open: /home/pierre/Git/gamegan/src/gan/wandb/offline-run-20210831_222838-26yvrcfy/run-26yvrcfy.wandb
2021-08-31 22:28:38,899 DEBUG   HandlerThread:20698 [handler.py:handle_request():124] handle_request: run_start
2021-08-31 22:28:38,902 DEBUG   HandlerThread:20698 [meta.py:__init__():34] meta init
2021-08-31 22:28:38,902 DEBUG   HandlerThread:20698 [meta.py:__init__():48] meta init done
2021-08-31 22:28:38,902 DEBUG   HandlerThread:20698 [meta.py:probe():205] probe
2021-08-31 22:28:38,909 DEBUG   HandlerThread:20698 [meta.py:_setup_git():195] setup git
2021-08-31 22:28:38,925 DEBUG   HandlerThread:20698 [meta.py:_setup_git():202] setup git done
2021-08-31 22:28:38,925 DEBUG   HandlerThread:20698 [meta.py:_save_pip():52] save pip
2021-08-31 22:28:38,926 DEBUG   HandlerThread:20698 [meta.py:_save_pip():66] save pip done
2021-08-31 22:28:38,926 DEBUG   HandlerThread:20698 [meta.py:_save_conda():73] save conda
2021-08-31 22:28:41,035 DEBUG   HandlerThread:20698 [meta.py:_save_conda():81] save conda done
2021-08-31 22:28:41,035 DEBUG   HandlerThread:20698 [meta.py:probe():247] probe done
2021-08-31 22:28:47,516 WARNING MainThread:20698 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-08-31 22:28:47,661 WARNING MainThread:20698 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-08-31 22:28:47,661 ERROR   MainThread:20698 [internal.py:wandb_internal():150] Internal process interrupted.
2021-08-31 22:28:48,114 INFO    SenderThread:20698 [sender.py:finish():947] shutting down sender
2021-08-31 22:28:48,473 INFO    WriterThread:20698 [datastore.py:close():288] close: /home/pierre/Git/gamegan/src/gan/wandb/offline-run-20210831_222838-26yvrcfy/run-26yvrcfy.wandb
2021-08-31 22:28:48,475 INFO    HandlerThread:20698 [handler.py:finish():658] shutting down handler
2021-08-31 22:28:48,476 INFO    MainThread:20698 [internal.py:handle_exit():78] Internal process exited
